function norm_derv_vec = fun_FineErrorFunctionDerv(cam_est_vec, ...
    cam_obs_vec, ...
    last_cam_est_vec, ...
    last_cam_obs_vec, ...
    cam_est_derv, ...
    depth_coarse_vec, ...
    depth_fine_vec, ...
    lambda, ...
    ParaSet);

    % Data term
    minus_vec = (cam_est_vec./last_cam_est_vec - cam_obs_vec./last_cam_obs_vec);
    data_derv = 2 * ((minus_vec./last_cam_est_vec)' * cam_est_derv)';

    % Regular Term
    r_minus_vec = (depth_fine_vec - depth_coarse_vec);
    regular_derv = 2 * r_minus_vec;

    derv_vec = data_derv + lambda * regular_derv;
    norm_derv_vec = derv_vec / norm(derv_vec);
end
