function error_value = fun_FineErrorFunction(cam_est_vec, ...
    cam_obs_vec, ...
    last_cam_est_vec, ...
    last_cam_obs_vec, ...
    depth_coarse_vec, ...
    depth_fine_vec, ...
    lambda, ...
    ParaSet)

    data_vec = (cam_est_vec./last_cam_est_vec - cam_obs_vec./last_cam_obs_vec);
    data_value = sum(data_vec.^2);

    regular_vec = (depth_fine_vec - depth_coarse_vec);
    regular_value = sum(regular_vec.^2);

    error_value = data_value + lambda * regular_value;
end
