%% Set start status of iteration
last_depth_mats = depth_mats{start_frame_num, 1};
for frame_idx = start_frame_num+1:1:data_frame_num
    % Initial
    fprintf('F%d:', frame_idx);
    beliefField = FillInitialBeliefField(camera_image{frame_idx, 1}, ...
        pattern, ...
        depth_mats{frame_idx-1, 1}, ...
        lineA, ...
        lineB, ...
        lineC, ...
        viewportMatrix, ...
        norm_sigma_u, ...
        voxelSize, ...
        halfVoxelRange);
    mask_mat = SetMaskMat(camera_image{frame_idx-1, 1}, ...
        camera_image{frame_idx, 1}, ...
        viewportMatrix);
    tmp_delta_depth_mat = GetDeltaDepthFromBeliefField(beliefField, ...
        viewportMatrix, ...
        voxelSize, ...
        halfVoxelRange);
%     tmp_depth_mat = GetDepthFromBeliefField(beliefField, ...
%         depth_mats{frame_idx-1, 1}, ...
%         viewportMatrix, ...
%         voxelSize, ...
%         halfVoxelRange);
    save(['depth_mat/', 'delta_frame_', num2str(frame_idx), '_iter_', '0', '.mat'], 'tmp_delta_depth_mat');
%     writepointcloud(tmp_depth_mat, ...
%         camMat, ...
%         ['point_cloud/', 'frame_', num2str(frame_idx), '_iter_', '0', '.txt'], ...
%         viewportMatrix);

    % Iteration
    for iter_idx = 1:10
        beliefField = BeliefFieldIterationFast(beliefField, ...
            mask_mat, ...
            camera_image{frame_idx, 1}, ...
            pattern, ...
            depth_mats{frame_idx-1, 1}, ...
            lineA, ...
            lineB, ...
            lineC, ...
            norm_sigma_u, ...
            norm_sigma_p, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange, ...
            halfNeighborRange);
        tmp_delta_depth_mat = GetDeltaDepthFromBeliefField(beliefField, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange);
        tmp_depth_mat = GetDepthFromBeliefField(beliefField, ...
            depth_mats{frame_idx-1, 1}, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange);
        save(['depth_mat/', 'delta_frame_', num2str(frame_idx), '_iter_', num2str(iter_idx), '.mat'], 'tmp_delta_depth_mat');
%         writepointcloud(tmp_depth_mat, ...
%             camMat, ...
%             ['point_cloud/', 'frame_', num2str(frame_idx), '_iter_', num2str(iter_idx), '.txt'], ...
%             viewportMatrix);
    end
    depth_mats{frame_idx, 1} = tmp_depth_mat;
end
