load GeneralPara.mat
load EpilinePara.mat

% Set initial frame info
fprintf('Initial...');
cam_mat_0 = double(imread([FilePath.main_file_path, ...
    'cam_0/', ...
    FilePath.img_file_path, ...
    FilePath.img_file_name, ...
    num2str(0), ...
    FilePath.img_file_suffix]));
cam_mat_1 = double(imread([FilePath.main_file_path, ...
    'cam_1/', ...
    FilePath.img_file_path, ...
    FilePath.img_file_name, ...
    num2str(0), ...
    FilePath.img_file_suffix]));
depth_mat = zeros(CamInfo.HEIGHT, CamInfo.WIDTH);
match_w_mat = zeros(CamInfo.HEIGHT, CamInfo.WIDTH);
match_h_mat = zeros(CamInfo.HEIGHT, CamInfo.WIDTH);
mask_mat = zeros(CamInfo.HEIGHT, CamInfo.WIDTH);
error_mat = zeros(CamInfo.HEIGHT, CamInfo.WIDTH);
fprintf('finished.\n');
